name: CD
on: 
  workflow_dispatch:

jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build & Save Docker Image
        if: github.ref == 'refs/heads/master'
        run: |
          docker build . -t web-converter
          mkdir build
          docker save web-converter | gzip > build/web-converter.tar.gz
      - name: Deploy Docker Image to Server
        if: github.ref == 'refs/heads/master'
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: build/
          server-dir: web-converter/
      - name: Load Docker Images on Server
        if: github.ref == 'refs/heads/master'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ../home/mauju.com/docker-images/web-converter
            ls -la
            docker load --input web-converter.tar.gz
            docker image prune -f